<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows10.0.19041.0;</TargetFrameworks>    
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <PackageId>Avae.Windows.Essentials</PackageId>
    <Version>1.0.0</Version>
    <Authors>cedricb</Authors>
    <Product>Avae.Windows.Essentials</Product>
    <Description>Portage of Microsoft.Maui.Essentials for Windows</Description>
    <PackageTags>maui;avalonia;essentials;crossplatform</PackageTags>
    <RepositoryUrl>https://github.com/cedric56/Avae.Windows.Essentials</RepositoryUrl>
    <PackageProjectUrl>https://github.com/cedric56/Avae.Windows.Essentials</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>Licence.md</PackageLicenseFile>
    <AssemblyName>Microsoft.Maui.Essentials</AssemblyName>
    <RootNamespace>Microsoft.Maui.Essentials</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.0" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.7.250606001" />
    <PackageReference Include="Microsoft.Maui.Graphics" Version="6.0.300" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="**\*.shared.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
    <Compile Include="**\*.shared.*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetPlatformIdentifier)' == 'windows' ">
    <Compile Include="**\*.uwp.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
    <Compile Include="**\*.uwp.*.cs" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
    <None Include="Licence.md" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
